---

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

#- name: upgrade apt packages
#  apt: upgrade=yes


- name: "Installing additional packages"
  apt: name={{item}} state=installed force=yes
  with_items:
       - build-essential
       - python-dev
       - libevent-dev
       - python-pip
       - liblzma-dev
       - swig
       - nginx         # for ngnix
       - nginx-extras  # for ngnix
       - apache2-utils
       - mc
       - git




